apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinispan
  namespace: jay
  labels:
    app: infinispan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infinispan
  template:
    metadata:
      labels:
        app: infinispan
        component: infinispan
    spec:
      containers:
        - name: infinispan
          image: infinispan/server:latest
          ports:
            - containerPort: 11222
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "128Mi"
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: infinispan-credentials
                  key: username
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: infinispan-credentials
                  key: password
            - name: DEBUG
              value: 'true'
---
apiVersion: v1
kind: Secret
metadata:
  name: infinispan-credentials
  namespace: jay
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
---
apiVersion: v1
kind: Service
metadata:
  name: infinispan
  namespace: jay
  labels:
    app: infinispan
spec:
  ports:
    - port: 11222
      targetPort: 11222
  selector:
    app: infinispan