apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: jay
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
        component: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: 'keycloak'
            - name: POSTGRES_USER
              value: 'keycloak'
            - name: POSTGRES_PASSWORD
              value: 'password'
          ports:
            - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: jay
  labels:
    app: postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql
